# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pir_folder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pirfolderpage',
            name='heading',
        ),
    ]
