# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pir_folder', '0003_pirfolderpage_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pirfolderpage',
            name='section',
            field=models.IntegerField(blank=True, choices=[(0, 'Front Page'), (1, 'Sector Overview'), (2, 'Killer Facts'), (3, 'Macro Context Between Countries'), (4, 'UK Market Overview'), (5, 'UK Business Info'), (6, 'UK Geographic Overview'), (7, 'Talent & Education'), (8, 'Sector Initiatives'), (9, 'R&D and Innovation'), (10, 'R&D Innovation Case Study - Written'), (11, "Who's Here?"), (12, 'Video Case Study'), (13, 'Services offered by DIT'), (14, 'Call to Action'), (15, 'Testimonials')], null=True),
        ),
    ]
