# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PirPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('heading', models.CharField(max_length=250)),
                ('body', models.CharField(max_length=250)),
                ('sectors', models.CharField(choices=[('renewable-energy', 'Renewable Energy'), ('automotive', 'Automotive'), ('financial-services', 'Financial Services'), ('creative-services', 'Creative Services'), ('technology', 'Technology'), ('life-sciences', 'Life Sciences')], max_length=32)),
                ('markets', models.CharField(choices=[('north-america', 'North America'), ('latin-america', 'Latin America'), ('europe', 'Europe'), ('turkey-caucasus', 'Turkey & Caucasus'), ('middle-east', 'Middle East'), ('africa', 'Africa'), ('south-asia', 'South Asia'), ('china', 'China'), ('asia-pacific', 'Asia Pacific')], max_length=32)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
