# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 13:11
from __future__ import unicode_literals

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pirpage',
            name='body',
            field=wagtailmarkdown.fields.MarkdownField(),
        ),
    ]
