# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pir', '0002_auto_20180214_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pirpage',
            old_name='markets',
            new_name='market',
        ),
        migrations.RenameField(
            model_name='pirpage',
            old_name='sectors',
            new_name='sector',
        ),
        migrations.RemoveField(
            model_name='pirpage',
            name='heading',
        ),
        migrations.AddField(
            model_name='pirpage',
            name='hero_image',
            field=models.ImageField(default='', upload_to='uploaded_images'),
        ),
        migrations.AlterField(
            model_name='pirpage',
            name='body',
            field=wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.CharBlock(max_length=250)), ('content', wagtailmarkdown.blocks.MarkdownBlock()))),
        ),
    ]
