# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-26 17:27
from __future__ import unicode_literals

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pir', '0015_auto_20180226_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pirpage',
            name='body',
            field=wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.StructBlock((('level', wagtail.core.blocks.ChoiceBlock(choices=[('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], max_length=2)), ('heading', wagtail.core.blocks.CharBlock(max_length=250))))), ('hero_image', wagtail.images.blocks.ImageChooserBlock()), ('content', wagtailmarkdown.blocks.MarkdownBlock()), ('content_with_footnotes', wagtail.core.blocks.StructBlock((('content', wagtailmarkdown.blocks.MarkdownBlock()), ('footnotes', wagtailmarkdown.blocks.MarkdownBlock())))), ('footnotes', wagtailmarkdown.blocks.MarkdownBlock()), ('logo', wagtail.images.blocks.ImageChooserBlock()), ('icon', wagtail.images.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('video', wagtail.core.blocks.CharBlock(max_length=256)), ('image_link', wagtail.core.blocks.StructBlock((('link', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))))))),
        ),
    ]
