# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-28 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pir', '0020_auto_20180227_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pirpage',
            name='section',
        ),
    ]
